services:
  db:
    container_name: nest_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: iot
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://omar:123@db:5432/iot
      RABBITMQ_URL: amqp://guest:guest@localhost:5672
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
