services:
  db:
    container_name: nest_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: iot
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    container_name: nest_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: iot
      RABBITMQ_DEFAULT_PASS: iot
    ports:
      - "5672:5672"   # App connection port
      - "15672:15672" # Management UI port

  app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://omar:123@db:5432/iot
      # FIX: Point to the 'rabbitmq' container, not localhost
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq

volumes:
  db-data:
